---
- name: UNIT FILE FOR SYSTEMD
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - reload systemd
    - restart node_exporter
  become: true
  when: ansible_service_mgr == "systemd"

- name: SERVICE node_exporter start
  service: 
    name: node_exporter
    state: started
    enabled: yes
  #when: ansible_service_mgr == "systemd"
