---
- name: VALIDATE URL {{ node_exporter_url }}
  uri: 
      url: "{{ node_exporter_url }}"
      return_content: false
  register: result
  failed_when: result.status != 200 

#- assert: { that: result.status == 200 }
