---
# handlers file for /root/Ansible/roles/node_exporter
- name: reload systemd
  systemd:
    daemon_reload: yes
    name: "node_exporter"
    state: started
    enabled: yes
  become: true

- name: restart node_exporter
  service:
    name: "node_exporter"
    state: "restarted"
  become: true
